dist: xenial
sudo: required
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'

cache:
  - apt
  - pip

notifications:
  email:
    on_failure: never

install:
  - pip install -r requirements.txt

# This stage is run against everything in the matrix (so every python version)
script:
  - pip install tox
  # Borrowed from flask-mongoengine
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')


jobs:
  include:
      # This adds a second parallel "test" stage (since we didn't specify
      # the stage name) just to run statick
    - stage: test
      python: '3.7'
      install:
        - pip install statick
      script: mkdir statick_output; statick . statick_output --profile self_check.yaml
    - stage: deploy
      python: '3.7'
      install:
        - pip install python-semantic-release
      script: 
        - git config --global user.name "semantic-release (via TravisCI)"
        - git config --global user.email "semantic-release@travis"
        - semantic-release publish
