dist: xenial
sudo: required
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'

cache:
  - apt
  - pip

notifications:
  email:
    on_failure: never

install:
  - pip install -r requirements.txt

# This stage is run against everything in the matrix (so every python version)
script:
  - pip install tox
  # Borrowed from flask-mongoengine
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')


jobs:
  include:
      # This adds a second parallel "test" stage (since we didn't specify
      # the stage name) just to run statick
    - stage: test
      python: '2.7'
      install:
        - pip install statick
      script: mkdir statick_output; statick . statick_output --profile self_check.yaml
    - stage: deploy
      python: '2.7'
      script: skip
      provider: pypi
      user: creffett
      password:
        secure: "pF63cjgW43BqhUHTGzl8qWZ0IifU76MjMHU2TF7kGrga9AZL2Vx0oZG4CKlxEg7DPJWMPoUEjsIRFWH6aFIH31VyJfTYzRHrlNogEFGNbkHPg6xAJpKbbmJVR+Zpf18PjNUxCTk5VgfINB4ycafuCtvCCbIE13CinU3uZR1092ZWk2n7sOaqzzT2D3/3y7gdNHPrSzXmw0Szzv/+wVN/bQSG3UAFA+/TGU3lqYtJ+mHR6PTl5XqOFsaTinLr3zh5IZKsR0WmLWN0rCtqau1KqZFmXHeWWux8qa7VSZBVsBeKgNjF7dzVS/25nIz4czsHs9zmG/oypLxoCmbq74fTpJ8zpg0ZAm2ZEA+ksVBAKVNtHrrPgKKbxmNtmzSjT7+aVRPxD33tEmxJoa0Em0pQ+gQyzCDVqes93BiXmnwwzaETW6n7KRWRa2fvazp7RIEnjEUPXfdevx5IYOU2099N7PoTlNzx0CLDtGFSWRjhNurQOdIZVCB/v742vP3Ys9z3GY6z2w9HnsFkRPF2OhcyB+A9n3pHsquSv/DdTuWUY4YS/A4fPCgJTNELauqLZUwsRhnuCBFdUwuDCuuWa++Ts9ekDtWVM7XJT1oIMEcw2ycZXoG4v+EV5fyA598WS9O2azIIUCbZ/CISgVnLve2rl1YLP4jksmrxBt/Nzp/71+4="
      on:
        tags: true
